### ISSUE TITLE
SIDENAV | Make it full height

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/SpartanProtocol-DAppV2#21]
The issue shows up between breakpoints:
~1200px wide <-> ~996px wide

![image](https://user-images.githubusercontent.com/26967164/108787556-fa5c9f00-75b0-11eb-99a0-22fb4af50571.png)

**Comment by dancespiele** [comment]
I see this is already fixed

**Comment by SamusElderg** [comment]
Not yet fixed; only on certain screen sizes @dancespiele 🤣

**Comment by jacobostel** [comment]
Can't replicate on  firefox and chrome...

**Comment by jacobostel** [comment]
someone did it, the sidebar 'collapses' when < 1200px

**Comment by SamusElderg** [comment]
Still not fixed 😄 all good ill fix it in a sec whilst I'm doing some other minor cosmetic stuff

**Comment by SamusElderg** [comment]
![image](https://user-images.githubusercontent.com/26967164/113467494-e17bbf00-9475-11eb-855b-d11ac5a4a470.png)
